### ISSUE TITLE
Appimage error safe browser

### ISSUE THREAD

**Issue by hamiltino** [maidsafe/sn_browser#1150]
## Prerequisites

- [ ] Using Appimage
- [ ] Using Ubuntu ~19 
- [ ] safe browser version 0.15.3

## Expected Behavior
Should run
## Current Behavior

[main 16:54:36.518] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[main 16:54:36.524] › whoops! there was an uncaught error:
[main 16:54:36.524] › In the main process
[main 16:54:36.524] › {"message":"libssl.so.1.0.0: cannot open shared object file: No such file or directory","name":"Error"}
[main 16:54:36.524] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by joshuef** [comment]
can you check if this is still an issue for you w/ latest alpha @hamiltino 🙇 
https://github.com/maidsafe/safe_browser/releases/tag/v0.16.0-alpha.2

**Comment by S-Coyle** [comment]
Closing legacy issues - this should now be resolved
