### ISSUE TITLE
Translate the project

### ISSUE THREAD

**Issue by wuniversales** [maidsafe/sn_browser#1168]
From what I see only the project is available in English, it would be nice to include more languages.
How can you contribute to the translation?

**Comment by joshuef** [comment]
great question @wuniversales !

The process would be making a PR against our translation file. 

Sadly that is quite bare at the moment. So not wholly practical right now, but if you're keen to get stuck in, I'll carve out some time to start updating this file.

**Comment by joshuef** [comment]
(If you are keen on translation, the safe network app is much better set up to get started (we have been using language files from the get go there).

You'd need to make a language file in the same folder, and then update the values for each translation we have here: https://github.com/maidsafe/safe-network-app/blob/master/app/locales/en.json

If you're keen, we can make an issue over on that repo and I can talk you through any edits 👍 

Let me know, and thanks for your interest!

**Comment by S-Coyle** [comment]
Closing legacy issues - no follow up
