### ISSUE TITLE
No connection, appimage error

### ISSUE THREAD

**Issue by wuniversales** [maidsafe/sn_browser#1169]
SO: Linux (Manjaro)
Safe Browser version: v0.15.4-linux-x64

No connection, appimage error
![image](https://user-images.githubusercontent.com/48658161/73197290-5c8a6c80-4131-11ea-8262-6bf5f284d9be.png)

Obviously if I have an internet connection.
Is it possible that the ports are blocked by cgnat?
Any way to skip that?

**Comment by joshuef** [comment]
You may not have the latest shared vault config. Please check [the guide over here](https://safenetforum.org/t/new-release-vault-phase-1-real-vault/29712) to ensure you've the latest config file downloaded 👍 

let me know how you get on

**Comment by S-Coyle** [comment]
Closing legacy issues - no follow up, presumed resolved
