### ISSUE TITLE
offer the safe browser as a snap package?

### ISSUE THREAD

**Issue by c-nv-s** [maidsafe/sn_browser#1182]
Is it possible to create a snap package of the safe browser?
https://snapcraft.io/

As an additional option for for download

**Comment by joshuef** [comment]
I'm not sure what's needed for this @c-nv-s , certainly not against more distribution channels.

If you want to dig in, maybe make a PR, I'll be happy to offer any guidance needed 👍

**Comment by S-Coyle** [comment]
Closing legacy issues - no follow up
