### ISSUE TITLE
Inconsistent naming and colours for apps

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/sn_browser#185]
Operation System: NA / all (tested with linux)
Beaker Version: Alpha 2 network

The Permissions Sidebar does not match the Authorised Apps display

* colour is different
* name is different

I would expect the colour and name to match.

Compare top left with bottom right in this cropped screengrab of safe browser:

![image](https://user-images.githubusercontent.com/1281387/30724208-cdc458d0-9f7f-11e7-8fa3-8f1817e63d83.png)

**Comment by S-Coyle** [comment]
Closing legacy issues - I believe this is all handled through the Safe Network App now, rather than via the browser
