### ISSUE TITLE
Dev tools cleared on page event

### ISSUE THREAD

**Issue by JPL1** [maidsafe/sn_browser#370]
Operation System and Version: Win 10
SAFE Browser Version: Peruse 0.7.0
Network: Alpha
Description:
The web dev tools window disappears on page refresh or other action (eg clicking a link), making it hard to see what's going on. Possibly linked to #368 ?
Steps to reproduce: 
Right click in page and select inspect element. Refresh page.

**Comment by shriram2301** [comment]
@JPL1  so I tried reproducing this. The logs get cleared on hitting refresh. This is the behavior in other browsers as well. If you wish to see the events and preserve the previous events you could try going to settings and click on preserve log. This should make the tools and the events that occurred prior to refresh or clicking a link continue to persist in case you wanted to view them.

**Comment by S-Coyle** [comment]
Closing legacy issues - seems this couldn't be replicated at the time
