### ISSUE TITLE
There seems to be an issue to login with some secret/password in v0.7.0

### ISSUE THREAD

**Issue by bochaco** [maidsafe/sn_browser#381]
As per this discussions there is probably a problem with some special characters when typing a secret/password to log in with browser 0.7.0 that needs to be investigated: https://safenetforum.org/t/account-login-error/25421/2

**Comment by zorani** [comment]
Hello!

I will test this again tomorrow. I'm not near laptop.

Here are m password details.

11 character alphanumeric secret.
Consists of, 4 alphabetic the rest numeric

15 character password.
Consists of one special character &
7 lower case, 2 upper case alphabetic
5 numeric.

**Comment by S-Coyle** [comment]
Closing legacy issues - this would be reported more if still an issue.
