### ISSUE TITLE
SAFE browser 1.0.0-rc2 - cannot right click in address bar to paste URL

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/sn_browser#466]
**Steps to reproduce:**

1. Open SAFE browser 1.0.0-rc2.
2. Copy a safe URL from another browser window.
3. Right click into SAFE browser address bar.

**Expected:**
User is given the option and is able to paste URL from right click. CTRL+V does work to do this.

**Actual:**
Right click does nothing, not able to paste.

**Environments:**
Found in Linux Mint 19 Cinnamon, native.
Reproduced in Ubuntu 18.04 VM.

**Comment by S-Coyle** [comment]
Closing legacy issue in favour of #849
