### ISSUE TITLE
Web Hosting Manager v0.5.1 hangs on authorisation with Browser v0.11.0

### ISSUE THREAD

**Issue by JPL1** [maidsafe/sn_browser#491]
It asks for authorisation but then hangs on "Waiting for Authorisation". I've tried revoking access and restarting - same result. Windows 10

**Comment by bochaco** [comment]
@JPL1 , thanks for reporting it. Are you still able to authorise WHM v0.5.0 with Peuse v0.7.0 with this account you are having issues with?

**Comment by JPL1** [comment]
@bochaco Yes WHM v0.5.0 with Peuse v0.7.0 authorises without any problems

**Comment by bochaco** [comment]
ok, that's fine then, and are you able to see anything in the browser logs, either from dev tools console or in the shell if you run it from the command line? If you are free later today I can go in a hangout with you to take a look at it, just let me know, you can send me PM on the forum to coordinate if you prefer

**Comment by JPL1** [comment]
Sure  - I'll take a look in a little while

**Comment by JPL1** [comment]
Hmmm ...  it's not letting me in now. Claiming my IP address needs resetting even though it's fine and 0.10.2 is working OK

**Comment by JPL1** [comment]
![authenticator-log](https://user-images.githubusercontent.com/12783198/50237497-fae7c280-03b4-11e9-8313-6a967996f2b9.png)
Here is the console output from Dev tools. The red warnings occur before I try to authenticate the WHM. Am I looking in the right place?

**Comment by bochaco** [comment]
This is definitely something with the IP address not being set/updated correctly or the connection, the red warning shouldn't be a problem at all. It seems you are having problems with seting the IP correctly. Are you even able to log in with the authenticator successfully on windows? are you able to authorise a webapp , e.g. WebID Mgr safe://webidmgr.dapp

**Comment by bochaco** [comment]
Just for the record, after analysing this a bit with @JPL1 (thanks a lot @JPL1 ), we narrowed it down to not being an issue with the WHM, the registry for the URI seems to be also ok, but when the browser is sending the response it seems the command is not executed or it's being trapped somewhere by the OS, we are not sure yet. Manually sending the response from a shell console gets the WHM to gain focus and connect succssfully with the network.
We are not seeing this behavour in other windows 10 we tried with so far, we'll keep investigating.

**Comment by joshuef** [comment]
I've come across this on OSX now, with the browser throwing an error when parsing the auth response, so nothing is being returned. Happen for WHM and other custom desktop apps...

**Comment by JPL1** [comment]
Update: this doesn't happen on the community network

**Comment by S-Coyle** [comment]
Closing legacy issue - WHM no longer in use
