### ISSUE TITLE
Can't use tab to navigate away from menu

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/sn_browser#525]
Steps to reproduce:
1. Navigate to one of the browser menus using ALT + letter (eg ALT + F).
2. Try to tab away from menu.

Expected:
Tab will change focus to another part of browser - in Firefox this will navigate into the address bar.

Actual:
Nothing happens. A workaround if for user to select select next / previous tab option from the File menu but is slightly cumbersome.

**Comment by joshuef** [comment]
May be dependant upon #410

**Comment by S-Coyle** [comment]
Closing legacy issue - seems to work fine now (macOS)
