### ISSUE TITLE
Keyboard shortcuts don't work while menu is open

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/sn_browser#528]
**Steps to reproduce:**
1. Open a menu using eg ALT + F for file.
2. Attempt to use keyboard shortcut for eg. opening a new window CTRL + W

**Expected:**
User should be able (in this example) to open a new browser window.
**Actual:**
Nothing happens.
![image](https://user-images.githubusercontent.com/44327924/51251860-3664b500-1992-11e9-8c25-5a52bbe54175.png)

**Comment by S-Coyle** [comment]
Closing legacy issues - seems to be resolved now (macOS)
