### ISSUE TITLE
Selectable Favicon

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/sn_browser#545]
On `Safe_browser 0.11.1 RC3` release, it is possible to select the favicon on double clicking the tab-bar. This issue was found on all three platforms (i.e., Mac, Linux and Windows).
This issue could be reproduced by just double clicking anywhere above a tab within the tab-bar.

![screenshot 2019-01-23 at 4 25 02 pm](https://user-images.githubusercontent.com/7814557/51602904-36cef400-1f2e-11e9-8f89-b34b3a4e52f9.png)

**Comment by S-Coyle** [comment]
Closing legacy issues - no longer reproducible (macOS)
