### ISSUE TITLE
OSX: Unable to reopen window on quit

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/sn_browser#552]
**STR**
1. Open browser
2. Quit browser window via red (x)
3. Click on the browser icon in the dock

**Expected behaviour**: browser window reopens 
**Displayed behaviour**: nothing happens. However the Apple menu at the top displays the browser menu options. I need to right-click the browser icon > quit > then relaunch the browser to enable use again 

![image](https://user-images.githubusercontent.com/35568923/51670565-d50a9a80-1fbe-11e9-93e8-fd6989bb8096.png)

**Comment by S-Coyle** [comment]
Closing legacy issues - duplicate of #551
