### ISSUE TITLE
App is authorised after permission is revoked, without showing auth popup

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/sn_browser#553]
SAFE Browser DEV build, and run with `--debug` option (v0.11.1 the version released today).
OS: Linux Ubuntu 18.10

Using SAFE Drive as the app (not tried with WHM), and run with `NODE_ENV=test`

If the authenticator padlock is 'closed' all seems well.

If the authenticator padlock is 'open', and I have revoked app permissions, the app is automatically authorised without the auth popup appearing.

What should happen is that the auth popup is shown so that the user gets to accept or deny (re)auth of the app.

**Comment by S-Coyle** [comment]
Closing legacy issues - seems this was only the dev build, so no longer applicable
