### ISSUE TITLE
Error message unhelpful

### ISSUE THREAD

**Issue by JPL1** [maidsafe/sn_browser#610]
safe://complements.valmarkpro/home.html results in this error message:

`Core error: Error while serialising/deserialising: Deserialise error: IoError: failed to fill whole buffer`

I guess this is because it uses home.html rather than index.html?

Safe Browser 0.11.0

**Comment by joshuef** [comment]
I'd be surprised about that, @JPL1 . Is the page attempting to auth or anything? The error reads like one for auth requests perhaps.

**Comment by S-Coyle** [comment]
Closing legacy issues - no reports of it being replicated since and site would have been on an old network, so no longer available
