### ISSUE TITLE
Not able to launch app from release folder on Ubuntu

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/sn_browser#750]
Tried building and packaging browser on Ubuntu, but after packaging there is no executable file found on the release folder, instead I'm seeing some `shared library` file, something like the following.

![image](https://user-images.githubusercontent.com/27578024/57453628-7ffc4700-7284-11e9-953d-b986015ace69.png)

not seeing any executable like

![image (1)](https://user-images.githubusercontent.com/27578024/57453661-973b3480-7284-11e9-9759-80454536a729.png)

and if I double click the file, I'm getting the following error

![image (2)](https://user-images.githubusercontent.com/27578024/57453716-b5089980-7284-11e9-8721-53b4761541c8.png)

But if I try to open the browser via terminal using `./safe-browser`, it works fine,

**Note:**
this happens after the commit `(4f453f67) feat( electron ): Update to electron v 4.x`. I'm able to run the browser from folder, if I build one commit before this, i.e, `(31c6d606) chore(lint): misc linting`.

**Comment by davidpbrown** [comment]
Looks old and could be closed?

https://github.com/maidsafe/safe_browser#Build
suggests no surprise as
```
linux

On Linux, the packaged application gets generated as a Shared Library file and hence cannot be run by double-clicking the executable. This is due to an issue with electron-builder( https://github.com/electron-userland/electron-builder/issues/3950 ). But the application can be run through the terminal. You can run the browser by running ./safe-browser.
```

**Comment by S-Coyle** [comment]
Closing legacy issue
