### ISSUE TITLE
Closing browser while loading the auth page at start, opening it again

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/sn_browser#752]
if you try to close the browser, before it is not fully loaded, i.e. while loading the auth page, it opens the browser again.

STR:
1. Open SAFE Browser, and try to close the browser while loading the auth page.
2. It closes and opens again, if you try to close the browser again in the same scenario, it closes and opens again, unless you wait for loading fully.

Tested on Ubuntu 18.04.1 LTS

**Comment by S-Coyle** [comment]
Closing legacy issues - no auth page now
