### ISSUE TITLE
Provide AutoUpdate Feature For SAFE Browser

### ISSUE THREAD

**Issue by manavbp** [maidsafe/sn_browser#833]
For the browser, at the moment we have electron-builder working and building individual packages for both mock and prod. And AutoUpdate works as well. But there is one blocker, which is electron-builder on packaging gives us a latest.yml for each build ( being mock and prod ). So ideally for windows, we have one latest.yml for mock and one for prod. And Electron-builder then uses that latest.yml to check for updates and notify the user. But the issue with it is we can't have both the latest.ymls in the same directory in the release. There is no way that electron-builder provides us to rename the yaml file either. On fixing this issue the target repo to which the autoUpdate config has would need to be changed to point to `safe_Browser`

**Comment by S-Coyle** [comment]
Closing legacy issues - auto update is now a working feature 😄
