### ISSUE TITLE
Toggle Developer Tools doesn't close dev tools window.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/sn_browser#851]
**Steps to reproduce:**
Testing v0.14-RC1
1. Use either menu `View` > `Toggle Developer Tools` or `Alt + Cmd +I` to open dev tools window.
2. Use either again to try to close the dev tools window.

**Expected:**
Dev tools windows toggles closed.
**Actual:**
Dev tools window stays open.

**Comment by manavbp** [comment]
Hey @calumcraig! Toggling DevTools does work once you toggle it on, click back on the window and the toggle shortcut again and it should work. This happens because the current window is no more in focus.

**Comment by calumcraig** [comment]
Removing the label `bug` as it is working as expected currently re @manavbp's comment above.

However, comparing this behaviour to Firefox and Chrome, those browsers toggle properly, ie I don't need to click back the main browser window in order to close the dev tools window.

Changing this to a feature request to consider whether to address it in a future release.

**Comment by S-Coyle** [comment]
Closing legacy issues
