### ISSUE TITLE
Launching experimental apps when experimental API mode is not switched on does not give warning

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/sn_browser#852]
**Steps to reproduce:**
Testing SAFE Browser v0.14-RC1 - macOS.
1. Launch browser and log into SAFE network.
2. Do NOT enable experimental mode.
3. Launch a web app that requires experimental API. eg WebID manager or Patter.

**Expected:**
An error message advising that experimental mode must be enabled is displayed (as previously happened).
**Actual:**
App requests authorisation but no error related to experimental mode is displayed.

**Comment by S-Coyle** [comment]
Closing legacy issues
