### ISSUE TITLE
Update message to direct users to GitHub examples repo

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/sn_browser#882]
If user has no apps authorised they are presented with the screen:
![image](https://user-images.githubusercontent.com/44327924/60354802-04399380-99c5-11e9-9a6d-3d28588fa49b.png)
Which directs them to click through to GitHub.
However, due to recent changes, non SAFE links no longer launch in the regular browser. When user clicks they see this:
![image](https://user-images.githubusercontent.com/44327924/60354884-30edab00-99c5-11e9-955d-396e0808e7e9.png)

Can we update the message on screen to instruct users to visit the GitHub link in their regular browser?

**Comment by calumcraig** [comment]
Furthermore, the page that the user is directed to is badly out of date - the first app listed is clearly labelled as deprecated:
![image](https://user-images.githubusercontent.com/44327924/60423635-88b72c80-9be6-11e9-9da9-423567285d11.png)
Do we really want to send users here?

**Comment by S-Coyle** [comment]
Closing legacy issues - safe authenticator is no longer a thing
